name: Qodana
on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.0.2
        with:
          args: -b,qodana.sarif.json


